ATTACK_METHOD : "inference"
ATTACK_CONFIG: 
    ROOFTOP_ANNOTATE: null
    ADVERSARIAL_PATCH: null
    DETECTOR: "single"
    TARGET_COMPONENT: null
    TRAINING_COMPONENTS: []

DATA_CONFIG:
    _BASE_CONFIG_: configs/dataset_configs/outdoor_demo_dataset.yaml
    GTBOXES:  null
    
    DATA_PROCESSOR:
        -   NAME: mask_points_and_boxes_outside_range
            REMOVE_OUTSIDE_BOXES: True
    
    ADVANCED_DATA_PROCESSOR: 
        -   NAME: remove_reflective
        -   NAME: sample_points_gpu
            NUM_POINTS: {
                'train': 16384,
                'test': 16384
            }

MODEL:
    _BASE_CONFIG_: configs/model_configs/pointrcnn.yaml
    CKPT_PATH: "/home/ksas/Public/model_zoo/pcdet/pointrcnn_7870.pth"