cd ../..
rm -rf output/train/loss_ablation/voxel_rcnn_car
python main.py --exp-name loss_ablation/voxel_rcnn_car/mislocalize_4 --roihead-attack --logit-frozen --stage-2-loss-reduce-func physical_loss --optim ifgsm --learning-rate 0.0005 --cfg-file configs/attack_configs/kitti/relevant_bounding_box_voxel_rcnn_car.yaml --device $1
python main.py --exp-name loss_ablation/voxel_rcnn_car/mislocalize_7 --roihead-attack --logit-frozen --stage-2-loss-reduce-func monocular_iou --optim ifgsm --learning-rate 0.0005 --cfg-file configs/attack_configs/kitti/relevant_bounding_box_voxel_rcnn_car.yaml --device $1
python main.py --exp-name loss_ablation/voxel_rcnn_car/mislocalize_9 --roihead-attack --logit-frozen --stage-2-loss-reduce-func score_multiply_iou3d --optim ifgsm --learning-rate 0.0005 --cfg-file configs/attack_configs/kitti/relevant_bounding_box_voxel_rcnn_car.yaml --device $1
python main.py --exp-name loss_ablation/voxel_rcnn_car/misrecognize_4 --roihead-attack --iou-frozen --stage-2-loss-reduce-func physical_loss --optim ifgsm --learning-rate 0.0005 --cfg-file configs/attack_configs/kitti/relevant_bounding_box_voxel_rcnn_car.yaml --device $1
python main.py --exp-name loss_ablation/voxel_rcnn_car/misrecognize_8 --roihead-attack --iou-frozen --stage-2-loss-reduce-func entropy_score_loss --optim ifgsm --learning-rate 0.0005 --cfg-file configs/attack_configs/kitti/relevant_bounding_box_voxel_rcnn_car.yaml --device $1
python main.py --exp-name loss_ablation/voxel_rcnn_car/misrecognize_9 --roihead-attack --iou-frozen --stage-2-loss-reduce-func score_multiply_iou3d --optim ifgsm --learning-rate 0.0005 --cfg-file configs/attack_configs/kitti/relevant_bounding_box_voxel_rcnn_car.yaml --device $1
python main.py --exp-name loss_ablation/voxel_rcnn_car/misrecognize_10 --roihead-attack --iou-frozen --stage-2-loss-reduce-func logit_multiply_iou3d --optim ifgsm --learning-rate 0.0005 --cfg-file configs/attack_configs/kitti/relevant_bounding_box_voxel_rcnn_car.yaml --device $1
python main.py --exp-name loss_ablation/voxel_rcnn_car/comprehensive_4 --roihead-attack  --stage-2-loss-reduce-func physical_loss --optim ifgsm --learning-rate 0.0005 --cfg-file configs/attack_configs/kitti/relevant_bounding_box_voxel_rcnn_car.yaml --device $1
python main.py --exp-name loss_ablation/voxel_rcnn_car/comprehensive_9  --roihead-attack --stage-2-loss-reduce-func score_multiply_iou3d --optim ifgsm --learning-rate 0.0005 --cfg-file configs/attack_configs/kitti/relevant_bounding_box_voxel_rcnn_car.yaml --device $1
