CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']

ATTACK_CONFIG: 
    ROOFTOP_ANNOTATE: "data/rooftop_approximation/rooftop_appro_kitti.pkl"
    DETECTOR: "rcnn"
    TARGET_COMPONENT: "PointHeadBox"
    TRAINING_COMPONENTS: []

DATA_CONFIG:
    _BASE_CONFIG_: configs/dataset_configs/kitti_dataset.yaml

    DATA_PROCESSOR:
        -   NAME: mask_points_and_boxes_outside_range
            REMOVE_OUTSIDE_BOXES: True
    
    ADVANCED_DATA_PROCESSOR: 
        -   NAME: remove_reflective
        -   NAME: sample_points_gpu
            NUM_POINTS: {
                'train': 16384,
                'test': 16384
            }


MODEL:
    _BASE_CONFIG_: configs/model_configs/pointrcnn_iou.yaml
    CKPT_PATH: "/home/ksas/Public/model_zoo/pcdet/pointrcnn_iou_7875.pth"