CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']

ATTACK_CONFIG: 
    ROOFTOP_ANNOTATE: "/home/ksas/uzuki_space/vehicle-shape-reconstruction/rooftop_appro_std.pkl"

    POINT_CLOUD_RANGE: [0, -39.68, -3, 69.12, 39.68, 1]
    DATA_PROCESSOR:
        - NAME: mask_points_and_boxes_outside_range
          REMOVE_OUTSIDE_BOXES: True

        - NAME: transform_points_to_voxels
          VOXEL_SIZE: [0.16, 0.16, 4]
          MAX_POINTS_PER_VOXEL: 32
          MAX_NUMBER_OF_VOXELS: {
            'train': 16000,
            'test': 40000
          }

DATA_CONFIG:
    _BASE_CONFIG_: configs/dataset_configs/kitti_dataset.yaml

    DATA_PROCESSOR:
        -   NAME: mask_points_and_boxes_outside_range
            REMOVE_OUTSIDE_BOXES: True

        -   NAME: sample_points
            NUM_POINTS: {
                'train': 16384,
                'test': 16384
            }

        -   NAME: shuffle_points
            SHUFFLE_ENABLED: {
                'train': True,
                'test': False
            }

MODEL:
    _BASE_CONFIG_: configs/model_configs/pointrcnn.yaml
    CKPT_PATH: "/home/ksas/Public/model_zoo/pcdet/pointrcnn_7870.pth"