CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']

ATTACK_CONFIG: 
    ROOFTOP_ANNOTATE: "/home/ksas/uzuki_space/vehicle-shape-reconstruction/rooftop_appro_std.pkl"
    DETECTOR: "rcnn"
    TARGET_COMPONENT: "PointHeadBox"

DATA_CONFIG:
    _BASE_CONFIG_: configs/dataset_configs/kitti_dataset.yaml

    DATA_PROCESSOR:
        -   NAME: mask_points_and_boxes_outside_range
            REMOVE_OUTSIDE_BOXES: True

        -   NAME: sample_points
            NUM_POINTS: {
                'train': 16384,
                'test': 16384
            }

        -   NAME: shuffle_points
            SHUFFLE_ENABLED: {
                'train': True,
                'test': False
            }
    ADVANCED_DATA_PROCESSOR: null

MODEL:
    _BASE_CONFIG_: configs/model_configs/pointrcnn.yaml
    CKPT_PATH: "/home/ksas/Public/model_zoo/pcdet/pointrcnn_7870.pth"