fit:
  seed_everything: 42
  trainer:
    logger:
      class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: "physical-attack"

    devices: 1
  data:
    # disabled_processing: ['constant_reflectness']
    class_names: ['Car', 'Pedestrian', 'Cyclist']
    batch_size: 1
    workers: 63
  model:
    save_scene_every_n_batches: 100
    adversary_config: null
   

test:
  seed_everything: 42
  trainer:
    logger:
      class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: "physical-attack"
        log_model: true
    devices: 1
  data:
    # disabled_processing: ['constant_reflectness']
    class_names: ['Car', 'Pedestrian', 'Cyclist']
    batch_size: 1
    workers: 63
  model:
    save_scene_every_n_batches: 100
    adversary_config: null