fit:
  trainer:
    logger:
      class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: "physical-attack"
        log_model: true
    devices: 1
  data:
    class_names: ['Car', 'Pedestrian', 'Cyclist']
    batch_size: 64
    workers: 63

test:
  trainer:
    logger:
      class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: "physical-attack"
        log_model: true
    devices: 1
  data:
    class_names: ['Car', 'Pedestrian', 'Cyclist']
    batch_size: 64
    workers: 63
  model:
    adversary_config: null